# Fly.io configuration for AdCopySurge Frontend
# https://fly.io/docs/reference/configuration/

app = "adcopysurge-frontend"
primary_region = "ord"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]
  dockerfile = "Dockerfile.fly"

[env]
  # Frontend Configuration
  NODE_ENV = "production"
  GENERATE_SOURCEMAP = "false"
  REACT_APP_ENVIRONMENT = "production"
  
  # API Configuration - Update after backend deployment
  REACT_APP_API_BASE_URL = "https://adcopysurge-backend.fly.dev"
  REACT_APP_API_URL = "https://adcopysurge-backend.fly.dev/api"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 50
    soft_limit = 40

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/"
    protocol = "http"
    tls_skip_verify = false

# Secrets to be set with `fly secrets set`:
# REACT_APP_SUPABASE_URL - Supabase project URL
# REACT_APP_SUPABASE_ANON_KEY - Supabase anon key
# REACT_APP_PADDLE_VENDOR_ID - Paddle vendor ID (optional)
# REACT_APP_GOOGLE_ANALYTICS_ID - Google Analytics ID (optional)
# REACT_APP_SENTRY_DSN - Sentry error tracking DSN (optional)
