# Netlify configuration for AdCopySurge Frontend
[build]
  publish = "build"
  command = "CI=false npm run build"
  
[build.environment]
  SKIP_PREFLIGHT_CHECK = "true"
  GENERATE_SOURCEMAP = "false"
  DISABLE_ESLINT_PLUGIN = "true"
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Production build context
[context.production]
  command = "CI=false npm run build"
  [context.production.environment]
    REACT_APP_ENVIRONMENT = "production"
    NODE_ENV = "production"

# Staging/develop branch context
[context.develop]
  command = "CI=false npm run build"
  [context.develop.environment]
    REACT_APP_ENVIRONMENT = "staging"
    NODE_ENV = "production"

# Branch deployments
[context.branch-deploy]
  command = "CI=false npm run build"
  [context.branch-deploy.environment]
    REACT_APP_ENVIRONMENT = "preview"

# Pull request deploys
[context.deploy-preview]
  command = "CI=false npm run build"
  [context.deploy-preview.environment]
    REACT_APP_ENVIRONMENT = "preview"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=()"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://js.stripe.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://adcopysurge-backend.fly.dev https://api.stripe.com; frame-src https://js.stripe.com;"

# Cache static assets
[[headers]]
  for = "/static/js/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "/static/css/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "/static/media/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.ico"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# API proxy redirects - Updated for Fly.io backend
[[redirects]]
  from = "/api/*"
  to = "https://adcopysurge-backend.fly.dev/api/:splat"
  status = 200
  force = false
  headers = {X-From = "Netlify"}

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# Edge functions (if needed)
# [[edge_functions]]
# function = "auth-check"
# path = "/dashboard/*"
