version: '3.8'

services:
  # ================================
  # 🔧 BACKEND SERVICE
  # ================================
  backend:
    image: ghcr.io/yourusername/adcopysurge/backend:${DOCKER_IMAGE_TAG:-latest}
    container_name: adcopysurge-backend-prod
    restart: unless-stopped
    
    environment:
      # Core Configuration
      - ENVIRONMENT=production
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=false
      - CORS_ORIGINS=https://adcopysurge.com,https://app.adcopysurge.com
      
      # Database
      - DATABASE_URL=${DATABASE_URL}
      - DB_POOL_SIZE=20
      - DB_MAX_OVERFLOW=40
      
      # AI Services
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY:-}
      
      # Authentication
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}
      
      # Email Configuration
      - SMTP_USERNAME=${SMTP_USERNAME:-}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-}
      - SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - FROM_EMAIL=${FROM_EMAIL:-support@adcopysurge.com}
      
      # Redis for caching and background tasks
      - REDIS_URL=redis://redis:6379/0
      
      # Background Tasks
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
      
      # File Storage
      - UPLOAD_DIR=/app/uploads
      - MAX_FILE_SIZE=10485760  # 10MB
      
      # Rate Limiting
      - RATE_LIMIT_ENABLED=true
      - RATE_LIMIT_PER_MINUTE=60
      
      # Monitoring
      - SENTRY_DSN=${SENTRY_DSN:-}
      - LOG_LEVEL=WARNING
      
      # Security
      - SECURE_SSL_REDIRECT=true
      - SESSION_COOKIE_SECURE=true
      - CSRF_COOKIE_SECURE=true
      
    ports:
      - "8000:8000"
      
    volumes:
      - backend_uploads:/app/uploads
      - backend_logs:/app/logs
      
    depends_on:
      - redis
      
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
      
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
        
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 2G
        reservations:
          cpus: "0.5"
          memory: 512M

  # ================================
  # 🎨 FRONTEND SERVICE  
  # ================================
  frontend:
    image: ghcr.io/yourusername/adcopysurge/frontend:${DOCKER_IMAGE_TAG:-latest}
    container_name: adcopysurge-frontend-prod
    restart: unless-stopped
    
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=https://api.adcopysurge.com
      - REACT_APP_ENVIRONMENT=production
      - REACT_APP_SUPABASE_URL=${SUPABASE_URL}
      - REACT_APP_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - REACT_APP_SENTRY_DSN=${REACT_APP_SENTRY_DSN:-}
      - GENERATE_SOURCEMAP=false
      
    ports:
      - "3000:3000"
      
    depends_on:
      - backend
      
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
      
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
        
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
        reservations:
          cpus: "0.25"
          memory: 256M

  # ================================
  # 📦 REDIS SERVICE
  # ================================
  redis:
    image: redis:7-alpine
    container_name: adcopysurge-redis-prod
    restart: unless-stopped
    
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru --save 900 1 --save 300 10 --save 60 10000
    
    volumes:
      - redis_data:/data
      
    ports:
      - "127.0.0.1:6379:6379"  # Only bind to localhost for security
      
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 768M
        reservations:
          cpus: "0.1"
          memory: 128M

  # ================================
  # 🔄 CELERY WORKER
  # ================================
  celery-worker:
    image: ghcr.io/yourusername/adcopysurge/backend:${DOCKER_IMAGE_TAG:-latest}
    container_name: adcopysurge-celery-worker-prod
    restart: unless-stopped
    
    command: celery -A app.celery_app worker --loglevel=WARNING --concurrency=4 --max-tasks-per-child=1000
    
    environment:
      # Same environment as backend
      - ENVIRONMENT=production
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY:-}
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
      - LOG_LEVEL=WARNING
      - SENTRY_DSN=${SENTRY_DSN:-}
      
    volumes:
      - backend_uploads:/app/uploads
      - backend_logs:/app/logs
      
    depends_on:
      - redis
      - backend
      
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
        
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 2G
        reservations:
          cpus: "0.5"
          memory: 512M

  # ================================
  # 📈 CELERY BEAT (Scheduler)
  # ================================
  celery-beat:
    image: ghcr.io/yourusername/adcopysurge/backend:${DOCKER_IMAGE_TAG:-latest}
    container_name: adcopysurge-celery-beat-prod
    restart: unless-stopped
    
    command: celery -A app.celery_app beat --loglevel=WARNING --schedule=/app/celerybeat-schedule --pidfile=/app/celerybeat.pid
    
    environment:
      - ENVIRONMENT=production
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
      - LOG_LEVEL=WARNING
      
    volumes:
      - celery_beat_data:/app
      - backend_logs:/app/logs
      
    depends_on:
      - redis
      - backend
      
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # ================================
  # 📊 MONITORING - NGINX
  # ================================
  nginx:
    image: nginx:alpine
    container_name: adcopysurge-nginx-prod
    restart: unless-stopped
    
    ports:
      - "80:80"
      - "443:443"
      
    volumes:
      - ./nginx/production.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
      - nginx_logs:/var/log/nginx
      
    depends_on:
      - frontend
      - backend
      
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
        
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.1"
          memory: 64M

  # ================================
  # 📊 MONITORING - PROMETHEUS (Optional)
  # ================================
  prometheus:
    image: prom/prometheus:latest
    container_name: adcopysurge-prometheus-prod
    restart: unless-stopped
    
    ports:
      - "127.0.0.1:9090:9090"
      
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
      
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=30d'
      - '--web.enable-lifecycle'
      
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

# ================================
# 📦 VOLUMES
# ================================
volumes:
  redis_data:
    driver: local
  backend_uploads:
    driver: local
  backend_logs:
    driver: local  
  nginx_logs:
    driver: local
  celery_beat_data:
    driver: local
  prometheus_data:
    driver: local

# ================================
# 🌐 NETWORKS
# ================================
networks:
  default:
    name: adcopysurge-production
    driver: bridge