version: '3.8'

services:
  # Backend API (Railway-optimized)
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.railway
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:postgres@postgres:5432/adcopysurge}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - DEBUG=${DEBUG:-False}
      - SECRET_KEY=${SECRET_KEY:-dev-super-secret-key-change-in-production-2024}
      - ALLOWED_HOSTS=["*"]
    volumes:
      - ./backend:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # PostgreSQL (for local development only)
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: adcopysurge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    profiles: ["local"]  # Only run with --profile local
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis (for local development only)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    profiles: ["local"]  # Only run with --profile local
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  redis_data:
