# Nixpacks configuration for Railway deployment
# This ensures Python 3.12 compatibility and proper build process

[variables]
PYTHONPATH = "/app/backend"

[phases.setup]
nixPkgs = ["python312", "gcc"]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv", 
  ". /opt/venv/bin/activate", 
  "pip install --upgrade pip setuptools wheel",
  "pip install -r requirements.txt -c constraints-py312.txt --no-cache-dir --prefer-binary"
]

[start]
cmd = "cd backend && echo 'Testing imports...' && python test_imports.py && echo 'Starting AdCopySurge API...' && PYTHONPATH=/app/backend gunicorn -c gunicorn-railway.conf.py main_production:app"
