[build]
builder = "NIXPACKS"

[build.env]
# Set Python version
NIXPACKS_PYTHON_VERSION = "3.11"

[deploy]
# Test imports first, then start the application
startCommand = "cd backend && echo 'Testing imports...' && python test_imports.py && echo 'Starting AdCopySurge API...' && PYTHONPATH=/app/backend gunicorn -c gunicorn-railway.conf.py main_production:app"

# Environment variables that need to be set in Railway dashboard
# Copy these variable names to Railway dashboard and set appropriate values
[variables]
# REQUIRED environment variables - must be set in Railway dashboard:
# DATABASE_URL = "postgresql://user:password@host:port/database"  # PostgreSQL connection string
# SECRET_KEY = "your-32-character-secret-key-here"  # Must be 32+ characters for JWT

# REQUIRED Supabase authentication (your app uses Supabase for auth):
# REACT_APP_SUPABASE_URL = "https://your-project-ref.supabase.co"  # Your Supabase project URL
# REACT_APP_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiI..."  # Your Supabase anon/public key
# SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiI..."  # Your Supabase service role key (optional but recommended)
# SUPABASE_JWT_SECRET = "your-jwt-secret"  # Your Supabase JWT secret (optional)

# AI Services (at least one required):
# OPENAI_API_KEY = "sk-..."  # OpenAI API key for AI features
# HUGGINGFACE_API_KEY = "hf_..."  # Optional: HuggingFace API key

# Security & CORS (update with your actual domains):
# ALLOWED_HOSTS = "your-app.railway.app,*.railway.app"  # Railway domain + any custom domains
# CORS_ORIGINS = "https://your-frontend.railway.app,https://your-custom-domain.com"  # Frontend origins

# Optional services:
# REDIS_URL = "redis://user:pass@host:port/db"  # If using Redis for caching
# SENTRY_DSN = "https://...@sentry.io/..."  # Error tracking

# Email configuration (optional):
# SMTP_SERVER = "smtp.gmail.com"
# SMTP_PORT = "587"
# SMTP_USERNAME = "your-email@gmail.com"
# SMTP_PASSWORD = "your-app-password"
# MAIL_FROM = "noreply@yourdomain.com"

# Payment processing (optional):
# PADDLE_VENDOR_ID = "your-vendor-id"
# PADDLE_API_KEY = "your-paddle-api-key"
# PADDLE_WEBHOOK_SECRET = "your-webhook-secret"
# PADDLE_ENVIRONMENT = "production"  # or "sandbox" for testing

# Application defaults (can be overridden):
ENVIRONMENT = "production"
DEBUG = "false"
LOG_LEVEL = "info"
HOST = "0.0.0.0"
# PORT is automatically set by Railway
