databases:
  - name: adcopysurge-db
    databaseName: adcopysurge
    user: adcopysurge_user
    plan: starter
    region: oregon
    ipAllowList: []  # Allow all IPs (can be restricted later)

services:

  # Redis Cache
  - type: redis
    name: adcopysurge-redis
    plan: starter
    region: oregon
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []

  # Backend API Service
  - type: web
    name: adcopysurge-backend
    runtime: docker
    plan: starter
    region: oregon
    dockerfilePath: ./backend/Dockerfile.render
    dockerContext: ./backend
    healthCheckPath: /health
    autoDeploy: true
    repo: https://github.com/yourusername/adcopysurge  # Update with your repo
    branch: main
    envVars:
      # Database & Redis - Auto-injected by Render
      - key: DATABASE_URL
        fromDatabase:
          name: adcopysurge-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: adcopysurge-redis
          type: redis
          property: connectionString
      
      # Application Configuration
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: HOST
        value: 0.0.0.0
      - key: APP_NAME
        value: AdCopySurge API
      - key: APP_VERSION
        value: 1.0.0
      
      # Security - Set these in Render Dashboard
      - key: SECRET_KEY
        sync: false  # Must be set manually in dashboard
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 60
      
      # Supabase Configuration - Set these in Render Dashboard
      - key: REACT_APP_SUPABASE_URL
        sync: false
      - key: REACT_APP_SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SUPABASE_JWT_SECRET
        sync: false
      
      # AI Services - Set these in Render Dashboard
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_MAX_TOKENS
        value: 2000
      - key: OPENAI_RATE_LIMIT
        value: 100
      - key: HUGGINGFACE_API_KEY
        sync: false
      
      # CORS Configuration
      - key: CORS_ORIGINS
        value: https://adcopysurge-frontend.onrender.com,http://localhost:3000,http://127.0.0.1:3000
      - key: ALLOWED_HOSTS
        value: adcopysurge-backend.onrender.com,*.onrender.com,localhost,127.0.0.1
      
      # Email Configuration - Set these in Render Dashboard  
      - key: SMTP_SERVER
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: MAIL_FROM
        value: noreply@adcopysurge.com
      - key: MAIL_FROM_NAME
        value: AdCopySurge
      
      # Paddle Billing Configuration - Set these in Render Dashboard
      - key: PADDLE_VENDOR_ID
        sync: false
      - key: PADDLE_API_KEY
        sync: false
      - key: PADDLE_WEBHOOK_SECRET
        sync: false
      - key: PADDLE_ENVIRONMENT
        value: production
      - key: PADDLE_API_URL
        value: https://vendors.paddle.com/api
      
      # Monitoring - Set these in Render Dashboard
      - key: SENTRY_DSN
        sync: false
      - key: SENTRY_ENVIRONMENT
        value: production
      - key: SENTRY_TRACES_SAMPLE_RATE
        value: 0.1
      
      # Performance Configuration
      - key: WORKERS
        value: 2
      - key: KEEP_ALIVE
        value: 2
      - key: MAX_CONNECTIONS
        value: 100
      
      # Feature Flags
      - key: ENABLE_ANALYTICS
        value: true
      - key: ENABLE_COMPETITOR_ANALYSIS
        value: false
      - key: ENABLE_PDF_REPORTS
        value: true
      - key: ENABLE_RATE_LIMITING
        value: true
      
      # Business Configuration
      - key: BASIC_PLAN_PRICE
        value: 49
      - key: PRO_PLAN_PRICE
        value: 99
      - key: FREE_TIER_LIMIT
        value: 5
      - key: BASIC_TIER_LIMIT
        value: 100
      - key: PRO_TIER_LIMIT
        value: 500

  # Frontend Static Site
  - type: static_site
    name: adcopysurge-frontend
    repo: https://github.com/yourusername/adcopysurge  # Update with your repo
    branch: main
    buildCommand: cd frontend && npm ci && npm run build
    staticPublishPath: ./frontend/build
    pullRequestPreviewsEnabled: true
    autoDeploy: true
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_BASE_URL
        value: https://adcopysurge-backend.onrender.com
      - key: REACT_APP_SUPABASE_URL
        sync: false  # Same as backend
      - key: REACT_APP_SUPABASE_ANON_KEY
        sync: false  # Same as backend
      - key: NODE_ENV
        value: production

