# Fly.io configuration for AdCopySurge Backend API
# https://fly.io/docs/reference/configuration/

app = "adcopysurge-backend"
primary_region = "ord"
kill_signal = "SIGINT"
kill_timeout = "10s"

[experimental]
  auto_rollback = true

[build]
  dockerfile = "Dockerfile.fly"
  builder = "dockerfile"
  
# Explicitly disable buildpacks
[build.args]
  BUILDPACK_DISABLE = "true"

[deploy]
  release_command = "python -m alembic upgrade head"

[env]
  # Application Configuration
  ENVIRONMENT = "production"
  DEBUG = "false"
  HOST = "0.0.0.0"
  APP_NAME = "AdCopySurge API"
  APP_VERSION = "1.0.0"
  
  # Security
  ALGORITHM = "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES = "60"
  
  # AI Configuration
  OPENAI_MAX_TOKENS = "2000"
  OPENAI_RATE_LIMIT = "100"
  
  # Email Configuration
  SMTP_SERVER = "smtp.gmail.com"
  SMTP_PORT = "587"
  MAIL_FROM = "noreply@adcopysurge.com"
  MAIL_FROM_NAME = "AdCopySurge"
  
  # Paddle Configuration
  PADDLE_ENVIRONMENT = "production"
  PADDLE_API_URL = "https://vendors.paddle.com/api"
  
  # Feature Flags
  ENABLE_ANALYTICS = "true"
  ENABLE_COMPETITOR_ANALYSIS = "false"
  ENABLE_PDF_REPORTS = "true"
  ENABLE_RATE_LIMITING = "true"
  
  # Business Configuration
  BASIC_PLAN_PRICE = "49"
  PRO_PLAN_PRICE = "99"
  FREE_TIER_LIMIT = "5"
  BASIC_TIER_LIMIT = "100"
  PRO_TIER_LIMIT = "500"

[[services]]
  protocol = "tcp"
  internal_port = 8000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/health"
    protocol = "http"
    tls_skip_verify = false

    [services.http_checks.headers]
      Content-Type = "application/json"

# Secrets to be set with `fly secrets set`:
# SECRET_KEY - Generate with: openssl rand -hex 32
# DATABASE_URL - PostgreSQL connection string 
# REDIS_URL - Redis connection string (optional)
# REACT_APP_SUPABASE_URL - Supabase project URL
# REACT_APP_SUPABASE_ANON_KEY - Supabase anon key
# SUPABASE_SERVICE_ROLE_KEY - Supabase service role key
# SUPABASE_JWT_SECRET - Supabase JWT secret
# OPENAI_API_KEY - OpenAI API key
# HUGGINGFACE_API_KEY - HuggingFace API key (optional)
# SMTP_USERNAME - Email username
# SMTP_PASSWORD - Email password
# PADDLE_VENDOR_ID - Paddle vendor ID
# PADDLE_API_KEY - Paddle API key
# PADDLE_WEBHOOK_SECRET - Paddle webhook secret
# SENTRY_DSN - Sentry error tracking DSN (optional)
